name: cursos
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  page_view_dot_indicator: ^2.1.0
  google_sign_in: ^6.2.1  
  toast: ^0.3.0
  flutter_share: ^2.0.0
  intl: ^0.19.0
  http: ^1.1.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true